@startuml domainModel
namespace DomainModel{
class Community    
class User
class Registred
class Anonimous
class CupGallery
class Cup
note left: name\nprice\ndescription\nsalable\nowner\n...
class Comment
class Transaction
class CreateUpdateDelete
Community *-->"1..*" User
Community *--> CupGallery
CupGallery o-->"0..*" Cup
Cup *--> Comment
Anonimous o--> CupGallery
Registred o--> CupGallery
User  <|-- Registred
User  <|-- Anonimous
Registred ..> Transaction
Registred ..> Comment
Registred ..> CreateUpdateDelete
CreateUpdateDelete ..> Cup
Transaction ..>Cup 
}
@enduml