@startuml domainModel
namespace DomainModel{
class Community    
class User
class Registred
class Anonimous
class CupGallery
class Cup
note left: name\nprice\ndescription\nsalable\nowner\n...
class Comment
class Transaction
class Management
Community *-->"1..*" User
Community *--> CupGallery
CupGallery o-->"0..*" Cup
Cup *-->"0..*" Comment
Anonimous o--> CupGallery
Registred o--> CupGallery
User  <|-- Registred
User  <|-- Anonimous
Registred ..> Transaction
Registred ..>"0..*" Comment
Registred ..> Management
Management ..> Cup
Transaction ..>Cup 
}
@enduml