@startuml domainModel
namespace DomainModel{
class Community    
class User
class Registred
class Anonimous
class CupGallery
class Cup
note left: name\nprice\ndescription\nsalable\nowner\n...
class Chat
class Transaction
class CreateUpdateDelete
Community *-->"1..*" User
Community *-->"1" CupGallery
CupGallery o-->"0..*" Cup
Cup *--> Chat
Anonimous *--> CupGallery
Registred *--> CupGallery
User  <|-- Registred
User  <|-- Anonimous
Registred ..> Transaction
Registred ..> Chat
Registred ..> CreateUpdateDelete
CreateUpdateDelete ..> Cup
Transaction ..>Cup 
}
@enduml