@startuml useCases
allowmixing
namespace useCases{
left to right direction
actor AnonimousUser
actor RegistredUser

usecase addCup
usecase getCup
usecase getCupList
usecase updateCup
usecase deleteCup
usecase transaction
usecase login
usecase signup
usecase logout
usecase getComment
usecase addComment
usecase deleteComment
usecase updateComment

AnonimousUser --> signup
AnonimousUser --> getCup
AnonimousUser --> getCupList
AnonimousUser --> login

transaction ..> getCup  : "<<include>>"

RegistredUser --> login
RegistredUser --> logout

RegistredUser --> addCup
addCup ..> getCup  : "<<include>>"
RegistredUser --> updateCup
updateCup ..> getCup  : "<<include>>"
RegistredUser --> deleteCup
deleteCup ..> getCup  : "<<include>>"
RegistredUser --> getCupList
getCupList ..> getCup  : "<<include>>"

RegistredUser --> addComment
addComment ..> getComment  : "<<include>>"
RegistredUser --> deleteComment
deleteComment ..> getComment  : "<<include>>"
RegistredUser --> updateComment
updateComment ..> getComment  : "<<include>>"

RegistredUser --> transaction
}
@enduml