@startuml useCases
allowmixing
namespace useCases{
left to right direction
actor AnonimousUser
actor RegistredUser

usecase CreateCup
usecase ReadCup
usecase ReadCupList
usecase UpdateCup
usecase DeleteCup
usecase Transaction
usecase Login
usecase Signup
usecase Logout
usecase ReadComment
usecase CreateComment
usecase DeleteComment
usecase UpdateComment

AnonimousUser --> Signup
AnonimousUser --> ReadCup
AnonimousUser --> ReadCupList
AnonimousUser --> Login

Transaction ..> ReadCup  : "<<include>>"

RegistredUser --> Login
RegistredUser --> Logout

RegistredUser --> CreateCup
CreateCup ..> ReadCup  : "<<include>>"
RegistredUser --> UpdateCup
UpdateCup ..> ReadCup  : "<<include>>"
RegistredUser --> DeleteCup
DeleteCup ..> ReadCup  : "<<include>>"
RegistredUser --> ReadCupList
ReadCupList ..> ReadCup  : "<<include>>"

RegistredUser --> CreateComment
CreateComment ..> ReadComment  : "<<include>>"
RegistredUser --> DeleteComment
DeleteComment ..> ReadComment  : "<<include>>"
RegistredUser --> UpdateComment
UpdateComment ..> ReadComment  : "<<include>>"

RegistredUser --> Transaction
}
@enduml