@startuml UseCaseContextRegistred
title UseCaseContextRegistred

state REGISTRED

[*] --> REGISTRED

REGISTRED --> OPENED_CUP
    note on link
        getCup
    end note

REGISTRED --> OPENED_CUP_LIST
    note on link
        getCupList
    end note     

OPENED_CUP_LIST --> CREATED_CUP
    note on link
        addCup
    end note 

OPENED_CUP_LIST --> OPENED_CUP
    note on link
        getCup
    end note               

OPENED_CUP --> MODIFIED_CUP
    note on link
        updateCup
        deleteCup
    end note   

OPENED_CUP --> OPENED_COMMENTS
    note on link
        getComment
    end note

OPENED_CUP --> OPENED_TRANSACTION
    note on link
        getTransaction
    end note

OPENED_COMMENTS --> MODIFIED_COMMENTS
    note on link
        addComment
        updateComment
        deleteComponent
    end note                 

REGISTRED --> LOGGED_OUT
    note on link
        logout
    end note

LOGGED_OUT --> [*]


@enduml