@startuml UseCaseContextAnonimous
title UseCaseContextAnonimous

state UNREGISTRED
state REGISTRED


[*] --> UNREGISTRED

UNREGISTRED --> REGISTRED
note on link
    signup
    login
end note

UNREGISTRED --> OPENED_CUP
    note on link
        getCup
    end note

UNREGISTRED --> OPENED_CUP_LIST
    note on link
        getCupList
    end note    

REGISTRED --> [*]

@enduml